name: test_regression_model
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8.12
  - pandas=1.1.4
  - pip=20.3.3
  - mlflow=1.14.1
  - scikit-learn=0.24.1
  - matplotlib=3.2.2
  - pillow=8.1.2
  - pip:
      - wandb==0.13.3
      - protobuf==3.20.1
      - numpy==1.23.4
      - git+https://github.com/pwirries/build-ml-pipeline-for-short-term-rental-prices.git#egg=wandb-utils&subdirectory=components
